# Tsunami Alert Web Dashboard Configuration

# Web Server Settings
HOST = '0.0.0.0'
PORT = 5000
DEBUG = True
SECRET_KEY = 'tsunami-alert-dashboard-2024'

# Video Settings
DEFAULT_RTSP_URL = ''
DEFAULT_RESIZE_WIDTH = 960
VIDEO_TIMEOUT = 30
FRAME_BUFFER_SIZE = 5

# Detection Thresholds (pixels)
DEFAULT_GARIS_EXTREME_Y = 180
DEFAULT_GARIS_SANGAT_TINGGI_Y = 210
DEFAULT_GARIS_TINGGI_Y = 230
DEFAULT_GARIS_SEDANG_Y = 250
DEFAULT_GARIS_RENDAH_Y = 280

# Overlay Settings
DEFAULT_LINE_THICKNESS = 1
DEFAULT_PEAK_THICKNESS = 2
DEFAULT_FONT_SCALE = 0.7
DEFAULT_FONT_THICKNESS = 2

# Alert Settings
DEFAULT_WA_COOLDOWN_SEC = 300
DEFAULT_SMS_COOLDOWN_SEC = 300
DEFAULT_EXTREME_THRESHOLD = 12
DEFAULT_ALERT_COOLDOWN_MIN = 30

# Data Settings
DEFAULT_CSV_PATH = 'deteksi_ombak.csv'
DEFAULT_SAMPLE_EVERY_SEC = 2
MAX_DATA_DISPLAY = 100

# Earthquake Settings
DEFAULT_MAGNITUDE_THRESHOLD = 5.0
DEFAULT_TSUNAMI_THRESHOLD = 6.0
DEFAULT_EARTHQUAKE_CHECK_INTERVAL = 300

# File Upload Settings
MAX_CONTENT_LENGTH = 16 * 1024 * 1024  # 16MB
UPLOAD_FOLDER = 'uploads'
ALLOWED_EXTENSIONS = {'json', 'csv'}

# Session Settings
PERMANENT_SESSION_LIFETIME = 3600  # 1 hour

# Logging Settings
LOG_LEVEL = 'INFO'
LOG_FILE = 'tsunami_dashboard.log'
LOG_MAX_BYTES = 10 * 1024 * 1024  # 10MB
LOG_BACKUP_COUNT = 5